Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    
    config.vm.provider "virtualbox" do |vb|
        vb.name = "01-vagrand_1.vm"
        # Customize the amount of memory and cpu on the VM:
        vb.memory = "512"
        vb.cpus = "1"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y apache2 php libapache2-mod-php
        rm /etc/apache2/ports.conf
        wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/1/ports.conf -O /etc/apache2/ports.conf
        rm /etc/apache2/sites-available/000-default.conf
        wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/1/000-default.conf -O /etc/apache2/sites-available/000-default.conf
        mkdir /var/www/dinamic
        wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/index.php -O /var/www/dinamic/index.php
        rm /var/www/html/index.html
        wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/index.html -O /var/www/html/index.html
        systemctl restart apache2
    SHELL
end