Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.network "private_network", ip: "192.168.21.11"
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.provider "virtualbox" do |slave1|
      slave1.memory = 512
      slave1.cpus = 1
    end
    slave1.vm.provision "file", source: "index.html", destination: "/home/vagrant/index.html"
    slave1.vm.provision "shell", inline: <<-SHELL
      #rpm -Uvh https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      service sshd restart
    SHELL
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.network "private_network", ip: "192.168.21.12"
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.provider "virtualbox" do |slave2|
      slave2.memory = 512
      slave2.cpus = 1
    end
    slave2.vm.provision "file", source: "index.php", destination: "/home/vagrant/index.php"
    slave2.vm.provision "shell", inline: <<-SHELL
      #rpm -Uvh https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      service sshd restart
    SHELL
  end

  config.vm.define "master.puppet" do |master|
    master.vm.network "private_network", ip: "192.168.21.13"
    master.vm.hostname = "master.puppet"
    master.vm.provider "virtualbox" do |master|
      master.memory = 1024
    end
    master.vm.provision "file", source: "inventory.ini", destination: "/home/vagrant/inventory.ini"
    master.vm.provision "file", source: "playbook.yml", destination: "/home/vagrant/playbook.yml"
    master.vm.provision "file", source: "r10k.yaml", destination: "/home/vagrant/r10k.yaml"
    master.vm.provision "shell", inline: <<-SHELL
      yum install -y ansible
      #rpm -Uvh https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      ansible-playbook -i inventory.ini playbook.yml -v
    SHELL
  end
end
