Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/home/vagrant/syncfolder/", disabled: false
    config.vm.network "private_network", ip: "192.168.22.10"
  
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        mkdir actions-runner && cd actions-runner    
        curl -o actions-runner-linux-x64-2.307.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.307.1/actions-runner-linux-x64-2.307.1.tar.gz
        tar xzf ./actions-runner-linux-x64-2.307.1.tar.gz
    SHELL

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release zip
        
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant

        rm /usr/bin/python
        cd /usr/bin
        ln -s python3 python
        apt-get install -y python3-pip
        ln -s pip3 pip
    SHELL
end