apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.label }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: ghcr.io/{{ .Values.image.repo-owner }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: app-port
            - containerPort: {{ .Values.container.APP-PORT }}