Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/home/vagrant/tmp", disabled: false
    config.vm.network "private_network", ip: "192.168.33.40"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus   = 2
        #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.gui = true
    end
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ca-certificates curl gnupg lsb-release gnome-core gnome
        
        #docker
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant

        #kubectl 
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

        #kubectx и kubens
        git clone https://github.com/ahmetb/kubectx.git /opt/kubectx
        ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
        ln -s /opt/kubectx/kubens /usr/local/bin/kubens
        
        #minikube
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube    
    SHELL

    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        minikube start
    SHELL
end