Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/home/vagrant", disabled: false
  
    config.vm.define "jenkins" do |jen|
      jen.vm.hostname = "jks.vm"
      jen.vm.network "private_network", ip: "192.168.24.10"

      jen.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y git build-essential default-jre
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
          /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null
        apt-get install -y ansible
        ansible-playbook playbook.yml
      SHELL
    end
  end