Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    config.vm.define "jks.vm" do |jen|
      jen.vm.hostname = "jks.vm"
      jen.vm.network "private_network", ip: "192.168.24.10"

      jen.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ansible
        ansible-playbook /vagrant/playbook.yml
      SHELL
    end
  end