Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    config.vm.define "jks.vm" do |jen|
      jen.vm.hostname = "jks.vm"
      jen.vm.network "private_network", ip: "192.168.24.10"

      jen.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      end  
    end
  end