Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Begin creating"
  
    config.vm.define "static" do |static|
        static.vm.box = "generic/debian11"
        static.vm.network "private_network", ip: "192.168.33.10"
        # Customize the amount of memory and cpu on the VM:
        static.vm.hostname = "static"
        static.vm.provider "virtualbox" do |static|
        static.memory = 512
        static.cpus = 1
        end

        static.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y apache2 php libapache2-mod-php
            echo "Complite static vm"
        SHELL
    end

    config.vm.define "dinamic" do |dinamic|
        dinamic.vm.box = "generic/debian11"
        dinamic.vm.network "private_network", ip: "192.168.33.11"
        # Customize the amount of memory and cpu on the VM:
        dinamic.vm.hostname = "dinamic"
        dinamic.vm.provider "virtualbox" do |dinamic|
        dinamic.memory = 512
        dinamic.cpus = 1
        end
        
        dinamic.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y apache2 php libapache2-mod-php
            echo "Complite dinamic vm"
        SHELL
    end

    config.vm.provision "shell", inline: "echo End creating"
    
end
