Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Begin creating"
  
    config.vm.define "static" do |static|
        static.vm.box = "generic/debian11"
        static.vm.network "private_network", ip: "192.168.33.10"
        # Customize the amount of memory and cpu on the VM:
        static.vm.hostname = "static"
        static.vm.provider "virtualbox" do |static|
        static.memory = 512
        static.cpus = 1
        end

        static.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y apache2 php libapache2-mod-php
            rm /var/www/html/index.html
            wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/index.html -O /var/www/html/index.html
            systemctl restart apache2
        SHELL
    end

    config.vm.define "dinamic" do |dinamic|
        dinamic.vm.box = "generic/debian11"
        dinamic.vm.network "private_network", ip: "192.168.33.11"
        # Customize the amount of memory and cpu on the VM:
        dinamic.vm.hostname = "dinamic"
        dinamic.vm.provider "virtualbox" do |dinamic|
        dinamic.memory = 512
        dinamic.cpus = 1
        end
        
        dinamic.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y apache2 php libapache2-mod-php
            rm /etc/apache2/sites-available/000-default.conf
            wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/2/000-default.conf -O /etc/apache2/sites-available/000-default.conf
            mkdir /var/www/dinamic
            wget https://raw.githubusercontent.com/narko2t/devops-hometasks/master/01-vagrant/index.php -O /var/www/dinamic/index.php
            systemctl restart apache2
        SHELL
    end

    config.vm.provision "shell", inline: "echo End creating"
    
end
