---
- name: Install Jenkins
  hosts: localhost
  become: true
  roles:
   - jenkins

- name: Configure Nexus
  hosts: nexus
  become: yes
  vars_files:
  - /vagrant/nexus_vars.yml
  
  pre_tasks:
  - include_tasks: nexus_pre_tasks.yml

  roles:
  - role: ansible-thoteam.nexus3-oss